#!/bin/bash
make clean
rm -rf config.cache scanbuild-output

VER=3.8
CCC_CC="/usr/bin/clang-${VER}"
ANALYZER="/usr/share/clang/scan-build-${VER}/ccc-analyzer"
CC="/usr/bin/clang-${VER}"
CFLAGS=" -g --coverage -DAST_DEVMODE -DSCANBUILD" 
SCANBUILD_FLAGS="-maxloop 10 
	-disable-checker deadcode.DeadStores \
	-enable-checker alpha.core.BoolAssignment \
	-enable-checker alpha.core.CallAndMessageUnInitRefArg \
	-enable-checker alpha.core.CastSize \
	-enable-checker alpha.core.CastToStruct \
	-enable-checker alpha.core.IdenticalExpr \
	-enable-checker alpha.core.PointerArithm \
	-enable-checker alpha.core.PointerSub \
	-enable-checker alpha.core.SizeofPtr \
	-enable-checker alpha.core.TestAfterDivZero \
	-enable-checker alpha.security.ArrayBound \
	-enable-checker alpha.security.ArrayBoundV2 \
	-enable-checker alpha.security.MallocOverflow \
	-enable-checker alpha.security.ReturnPtrRange \
	-enable-checker alpha.security.taint.TaintPropagation \
	-enable-checker alpha.unix.MallocWithAnnotations \
	-enable-checker alpha.unix.PthreadLock \
	-enable-checker alpha.unix.SimpleStream \
	-enable-checker alpha.unix.Stream \
	-enable-checker alpha.unix.cstring.BufferOverlap \
	-enable-checker alpha.unix.cstring.NotNullTerminated \
	-enable-checker alpha.unix.cstring.OutOfBounds"
	
if [ -z "`grep fblocks ${ANALYZER}`" ];then
	# fix analyzer
	sudo cp ${ANALYZER} ${ANALYZER}.bak
	sudo sed 	-e "s!'-miphoneos-version-min' => 0!'-miphoneos-version-min' => 0, '-fblocks' => 0!g" \
			-e "s!'--serialize-diagnostics' => 1!'--serialize-diagnostics' => 1, '-fblocks' => 0!g" \
			-i ${ANALYZER}
fi
/usr/bin/scan-build-${VER} --use-cc="${CC}" -disable-checker deadcode.DeadStores -o scanbuild-output ./configure --without-ccache  --enable-video --enable-video-layer --enable-devdoc --enable-conference --enable-advanced-functions --enable-distributed-devicestate CFLAGS="${CFLAGS}" $*
/usr/bin/scan-build-${VER} --use-cc="${CC}" -disable-checker deadcode.DeadStores -o scanbuild-output make
