/*
 * automatically generated by ./create_config.sh Do 8. Nov 20:34:24 CET 2007
 */

#ifndef CHAN_SCCP_CONFIG_H
#define CHAN_SCCP_CONFIG_H
#define ASTERISK_CONF_1_2

#define CS_SCCP_PARK
#define CS_SCCP_PICKUP
#define CS_SCCP_REALTIME
#define CS_AST_HAS_TECH_PVT
#define CS_AST_HAS_BRIDGED_CHANNEL
#define CS_AST_CHANNEL_HAS_CID
#define CS_AST_CONTROL_HOLD
#define sccp_copy_string(x,y,z) ast_copy_string(x,y,z)
#define CS_AST_HAS_FLAG_MOH
#define CS_AST_HAS_ENDIAN
#define CS_AST_HAS_STRINGS
#define CS_AST_HAS_NEW_VOICEMAIL
#define CS_AST_HAS_NEW_HINT
#define CS_AST_HAS_NEW_DEVICESTATE
#define CS_AST_DEVICE_RINGING
#define CS_AST_HAS_AST_GROUP_T
#define CS_AST_HAS_APP_SEPARATE_ARGS
#define sccp_app_separate_args(x,y,z,w) ast_app_separate_args(x,y,z,w)
#define CS_AST_HAS_EXTENSION_RINGING

#endif /* CHAN_CAPI_CONFIG_H */

