Document: chan-sccp-b
Title: Debian chan-sccp-b Manual
Author: <insert document author here>
Abstract: This manual describes what chan-sccp-b is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/chan-sccp-b/chan-sccp-b.sgml.gz

Format: postscript
Files: /usr/share/doc/chan-sccp-b/chan-sccp-b.ps.gz

Format: text
Files: /usr/share/doc/chan-sccp-b/chan-sccp-b.text.gz

Format: HTML
Index: /usr/share/doc/chan-sccp-b/html/index.html
Files: /usr/share/doc/chan-sccp-b/html/*.html
