#!/bin/bash
# FILE: Update configure/makefile scripts
# COPYRIGHT: chan-sccp-b.sourceforge.net group 2009
# CREATED BY: Diederik de Groot <ddegroot@sourceforge.net>
# LICENSE: This program is free software and may be modified and distributed under the terms of the GNU Public License.
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# DATE:     $Date: $
# REVISION: $Revision: $

echo "Running aclocal"
aclocal --force -I autoconf
echo "Running libtoolize"
libtoolize --copy --force --quiet
echo "Running autoheader"
autoheader
echo "Running automake"
automake --add-missing --copy --force-missing
echo "Running autoconf"
autoconf
echo "Running configure"
./configure
echo "Running make"
make
echo "Adding Current Revision to NEWS file"
echo TRUNK_r`svn info |grep Revision |awk -F:\  '{print $2}'`: Generated Release on `date +"%Y/%M/%d"` >>NEWS
echo "Running make dist"
make dist

