#!/bin/sh
SCCP_BRANCH="unknown"
SCCP_VERSION="unknown"
SCCP_REVISION="unknown"
REPOS_TYPE="unknown"

if test -d .svn || test -d ../.svn || test -d ../../.svn;then
  if test ! -z "`which svn`"; then
    #if test "`basename $(svn info .| grep -i ^URL: | cut -d ' ' -f 2)`" != "trunk"; then
    #    SCCP_VERSION="`basename $(svn info .| grep -i ^URL: | cut -d ' ' -f 2)`"
    #    SCCP_BRANCH="STABLE"
    #else
      if test -f .version; then
        SCCP_VERSION="`cat .version|cut -d_ -f1`"
        SCCP_BRANCH="`cat .version|cut -d_ -f2`"
      else 
        SCCP_VERSION="TRUNK"
        SCCP_BRANCH="TRUNK"
      fi
      if test "$SCCP_VERSION" = "$SCCP_BRANCH"; then
        SCCP_BRANCH="TRUNK"
      fi
    #fi
    SCCP_REVISION="`svnversion . |cut -d: -f2 | cut -dM -f1`"
    REPOS_TYPE="SVN"
  fi
elif test -d .hg || test -d ../.hg | test -d ../../.hg; then
  if test ! -z "`which hg`"; then
    SCCP_VERSION="`cat .hg/hgrc |grep http|awk '{print $3}'|tr "/" "\n"|tail -n2|head -n1`"
    if grep -q "default" .hg/branch; then
      SCCP_BRANCH="TRUNK"
    else 
      SCCP_BRANCH="`cat .hg/branch`"
    fi
    SCCP_REVISION="`hg parents|grep changeset|tail -n1|sed 's/\(.*:\)\(.*\)\(:.*\)/\2/g'|sed 's/\ //g'`"
    REPOS_TYPE="HG"
  fi
elif test -d .git || test -d ../.git || test -d ../../.git;then
  if test ! -z "`which git`"; then
    SCCP_VERSION="`cat .version|cut -d_ -f1`"
    if test "`git branch | awk '{print $2}' | sed 's/\n//g'`" = "master"; then
      SCCP_BRANCH="TRUNK"
    else 
      SCCP_BRANCH="`git branch| grep "*" |awk '{print $2}' | sed 's/\\n//g'`"
    fi
    SCCP_REVISION="`git describe --always`"
    REPOS_TYPE="GIT"
  fi
fi

if test "$SCCP_VERSION" = "unknown"; then
  SCCP_BRANCH="TRUNK"
  SCCP_VERSION="`cat .version|cut -d_ -f1`"
  if test ! -z "`grep '_' .version`" ; then
    SCCP_BRANCH="`cat .version|cut -d_ -f2`"
  fi
  if test -f .revision; then
    SCCP_REVISION=`cat .revision |grep VCS_NUM |cut -d= -f2|cut -d\" -f2`
  fi
  REPOS_TYPE="TGZ"
fi

if test "$1" != "silent"; then
	echo SCCP_VERSION: $SCCP_VERSION 
	echo SCCP_BRANCH: $SCCP_BRANCH 
	echo SCCP_REVISION: $SCCP_REVISION
	echo REPOS_TYPE: $REPOS_TYPE
fi
