/*!
 * \file        common.h
 * \brief       SCCP Common Include File
 * \author      Diederik de Groot <dkgroot [at] talon.nl>
 * \note        This file is automatically generated by configure
 * \note        Do not change this file. Change will be lost when running configure
 */
#pragma once

#define ENUMMACRO_GENHEADER	1
#define ENUMMACRO_GENFUNCTION	2
#define ENUMMACRO_SPARSE 	1
#define ENUMMACRO_INCREMENTAL 	0

#if HAVE_STRING_H
#include <string.h>
#endif
#if HAVE_STDIO_H
#include <stdio.h>
#endif
#if HAVE_STDLIB_H
#include <stdlib.h>
#endif
#if HAVE_ERRNO_H
#include <errno.h>
#endif
#if HAVE_CTYPE_H
#include <ctype.h>
#endif
#if HAVE_UNISTD_H
#include <unistd.h>
#endif
#if HAVE_ASSERT_H
#include <assert.h>
#endif
#if HAVE_INTTYPES_H
#include <inttypes.h>
#endif
#if HAVE_STDBOOL_H
#include <stdbool.h>
#endif

#include "define.h"
#include "forward_declarations.h"
#include "sccp_enum.h"
#include "sccp_dllists.h"
#include "sccp_threadpool.h"
#include "sccp_debug.h"
#include "sccp_globals.h"
#include "sccp_rtp.h"
#include "sccp_refcount.h"
#include "sccp_event.h"
#include "pbx_impl/pbx_impl.h"
#include "sccp_callinfo.h"

// kate: indent-width 8; replace-tabs off; indent-mode cstyle; auto-insert-doxygen on; line-numbers on; tab-indents on; keep-extra-spaces off; auto-brackets off;
